Беляев Станислав, 3-й курс, SD, Задача CLI
StasBel/sd-homework pull request #1
Opened 2016-10-26 21:43 UTC by StasBel

@yurii-litvinov

2016-11-06 20:10 UTC, yurii-litvinov requested changes
На диаграмме стрелки наследования не в ту сторону, треугольники должны быть у класса-предка. С агрегациями, кажется, то же самое.

Ещё, кстати, на диаграмме сильно не хватает команд.

Поправьте, пожалуйста.

2016-11-06 20:10 UTC, yurii-litvinov commented on .gitignore
> +src/main/kotlin/ru/spbau/mit/belyaev/Main.kt
Почему? :)

2016-11-06 20:10 UTC, yurii-litvinov commented on .gitignore
> +src/main/kotlin/ru/spbau/mit/belyaev/Main.kt
Вообще, REPL-цикл же должен быть где-то

2016-11-06 20:10 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Context.kt
> +        const val BASH_PATH = "/bin/bash"
Под виндой такое не работает :)

2016-11-06 20:10 UTC, yurii-litvinov commented on README.md
> +Есть базовый абстрактный клаас Stream, от которого наследуются CharStream, LexemeStream и CommandStream, которые реализуют функционал обертки для входной строки, разбиения на лексемы и парсинга соотв
"абстрактный кла**сс**", опечатка.

2016-11-06 20:10 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Context.kt
> +     * @param input input in string representaion or null
representa**t**ion

2016-11-06 20:10 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Context.kt
> +     * @param value value
Не очень ценный комментарий. Лучше хотя бы "value to assign"

2016-11-06 20:10 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Shell.kt
> +// TODO продокументировать все классы + добавить dokka зависимость в gradle
Сделано, вроде.

2016-11-06 20:10 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Shell.kt
> +    private fun LexemeStream.concatenatePlaintTextsAndRefs(): LexemeStream {
Plaint?

2016-11-06 20:10 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/debug/Error.kt
> +class Error(errorMessage: String) : Notification(errorMessage, Level.ERROR)
Здесь и ниже тоже надо комментарии

2016-11-07 18:28 UTC, StasBel commented
Исправил.

2016-12-18 14:22 UTC, yurii-litvinov commented
Так всё-таки, насчёт REPL-цикла, как это всё запустить, чтобы можно было писать команды и видеть результат?

2016-12-18 14:55 UTC, yurii-litvinov requested changes

2016-12-18 14:55 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Main.kt
> +            print(shell.execute(line!!));
Так если что-то при исполнении копанды пойдёт не так, весь шелл закончит работу. Например, если опечататься в имени команды. Хочется, чтобы ругалось и ждало следующую команду, а не падало.

2016-12-18 15:29 UTC, yurii-litvinov requested changes

2016-12-18 15:29 UTC, yurii-litvinov commented on gradlew
> +    for name in "$@" ; do
Гм?

2016-12-18 15:29 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/lexer/Lexeme.kt
> +sealed class Lexeme(private val str: String = "") {
Нужно больше содержательных комментариев, здесь и ниже

2016-12-18 16:48 UTC, StasBel commented on gradlew
> +    for name in "$@" ; do
Так gradlew же сам генерится? Ну я по крайней мере ничего не изменял.

2016-12-18 16:49 UTC, StasBel commented on src/main/kotlin/ru/spbau/mit/belyaev/Main.kt
> +            print(shell.execute(line!!));
Нет. Сейчас, если сделать опечатку в имени команды, то все равно будет ждать следующую (только что попробовал). Шелл падает, если, например скобочки не образуют правильно скобочную последовательность, но ведь в реальном shell'e в таком случае shell будет запрашивать продолжение команды на следующих строчках, и так далее пока конкатенация всех не даст корректную строку.
Напишите команду с ошибкой в имени на которой все падает.

2016-12-18 16:49 UTC, yurii-litvinov commented on gradlew
> +    for name in "$@" ; do
Есть подозрение, что это сделала IDEA, выполнив поиск с заменой по проекту, она так любит

2016-12-18 16:50 UTC, yurii-litvinov approved these changes

2016-12-18 16:55 UTC, yurii-litvinov commented on src/main/kotlin/ru/spbau/mit/belyaev/Main.kt
> +            print(shell.execute(line!!));
аа, потому что оно пытается запустить bash, в надежде, что он есть, и падает, если нету

2025-07-25 18:54 UTC, closed without merging